import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import org.hibernate.Query;

public class Login extends HttpServlet {
 
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        HttpSession session = request.getSession();
        PrintWriter out = response.getWriter();
        
        String email = session.getParameter("email");
        String pass = request.getParameter("contrasena");
        
        if(checkUser(email, pass))
        {
            RequestDispatcher rs = request.getRequestDispatcher("Welcome");
            rs.forward(request, response);
        }
        else
        {
           out.println("Username or Password incorrect");
           RequestDispatcher rs = request.getRequestDispatcher("index.html");
           rs.forward(request, response);
        }
    }
    public static boolean checkUser(String email,String pass){
      boolean st = false;

      try{
        org.hibernate.Transaction tx = session.beginTransaction();
        Query q = seesion.createQuery("From User as user where user.email =:param1 and user.contrasena =:param2");
        Query.setString("param1",email);
        Query.setString("param2",pass);
        // Compare User objects to the one generated by this usr/pass combination
      }
      catch(Exception e){
        e.printStackTrace();
      }
      return st;                    
    }
}
