import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import webapp.*;
import org.hibernate.*;

public class Login extends HttpServlet {
 
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        HttpSession session = request.getSession();
        PrintWriter out = response.getWriter();
        String email = session.getParameter("email");
        String pass = session.getParameter("contrasena");
      		boolean checkuser = false;
      		try{
        	   org.hibernate.Transaction tx = session.beginTransaction();
        	   Query q = seesion.createQuery("From User as user where user.email =:param1 and user.contrasena =:param2");
        	   Query.setString("param1",email);
        	   Query.setString("param2",pass);
		          checkuser = true;
        	   // Compare User objects to the one generated by this usr/pass combination
        } catch(Exception e){
        	   e.printStackTrace();
      		}                    
        if(checkuser)
        {
            out.println("Autenticación correcta.");
            RequestDispatcher rd = request.getRequestDispatcher("/** VISTA PRINCIPAL **/");
            rd.forward(request, response);
        }
        else
        {
           out.println("Usuario o contraseña incorrectas.");
           RequestDispatcher rd = request.getRequestDispatcher("index.html");
           rd.forward(request, response);
        }
    }
}
